version: '3.8'

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lucid
      MYSQL_USER: lucid
      MYSQL_PASSWORD: secret
